# Hosting Settings
MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.3"
Host: # Host Name
LinksUseHttps: true # Do we use HTTPS

# Branding
SiteTitle: Architecture Repository
SiteDescriptions: A collection of articles about architecture.
Copyright: => $"Copyright © {DateTime.Now.Year}"
Layout: /_layout.cshtml

# Post Settings
PostSources: "/architecture/**/*.md"
# IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
