# Hosting Settings
MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.3"
Host: red-sand-078a6ea03.3.azurestaticapps.net # Host Name
LinksUseHttps: true # Do we use HTTPS

# Branding
SiteTitle: Architecture Repository
SiteDescriptions: An assortment of articles about architecture.
Copyright: => $"Copyright © {DateTime.Now.Year}"
Layout: /_layout.cshtml
Image: https://brenstermedia.blob.core.windows.net/media/media/images/header01.png

# Post Settings
PostSources:
- posts/**/*.md
- posts/**/**/*.md
# IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
GenerateSearchIndex: true