# Hosting Settings
MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.3"
Host: red-sand-078a6ea03.3.azurestaticapps.net # Host Name
LinksUseHttps: true # Do we use HTTPS

# Branding
SiteTitle: Architecture Repository
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
SiteDescriptions: An assortment of articles about architecture
Copyright: => $"Copyright James Brewster© {DateTime.Now.Year}"
Layout: /_layout.cshtml
Image: https://brenstermedia.blob.core.windows.net/media/media/images/header01.png

# Post Settings
PostSources: posts/**/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
DateTimeInputCulture: "en-GB"
DateTimeDisplayCulture: "en-GB"
GenerateSearchIndex: true