# Hosting Settings
MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.3"
Host: open-ea.brenster.uk # Host Name
LinksUseHttps: true # Do we use HTTPS

# Branding
SiteTitle: Architecture Repository
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
SiteDescriptions: Assorted articles about architecture
Copyright: => $"Copyright James Brewster© {DateTime.Now.Year}"
Layout: /_layout.cshtml
HeaderImage: /media/header01.png
Image: |
  =>
  {
    string Host = Context.GetString("Host");
    bool LinksUseHttps = Context.GetBool("LinksUseHttps");
    string HeaderImage = Context.GetString("HeaderImage");
    string result = Host + HeaderImage;
    switch (LinksUseHttps)
    {
      case false:
        result = "http://" + result;
        break;
      
      case true:
        result ="https://" + result;
        break;
    }
    return result;
  }

# Post Settings
# PostSources: posts/*

PostSources: |
  =>
  {
    Matcher PostSources = new();
    PostSources.AddIncludePatterns(new[] { "posts/*"});
    return PostSources;
  }
PageSources: pages/*
Published: 2001-01-01
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
DateTimeInputCulture: "en-GB"
DateTimeDisplayCulture: "en-GB"
GenerateSearchIndex: true
